package ru.eljke.tournamentsystem.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

@Schema(name = "Tournament Data Transfer Object")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TournamentDTO {
    @Schema(name = "Autogenerated ID")
    private Long id;
    @Schema(name = "Tournament name")
    private String name;
    @Schema(name = "Tournament city")
    private String city;
    @Schema(name = "Tournament organizing school")
    private String organizingSchool;
    @Schema(name = "Start date and time of the tournament")
    private String startDateTime;
    @Schema(name = "End date of the tournament")
    private String endDate;
    @Schema(name = "Min number of participants")
    private Integer minParticipants;
    @Schema(name = "Max number of participants")
    private Integer maxParticipants;
    @Schema(name = "Min age to participate in the tournament")
    private Integer minAgeToParticipate;
    @Schema(name = "Max age to participate in the tournament")
    private Integer maxAgeToParticipate;
    @Schema(name = "Tournament stage")
    private String stage;
    @Schema(name = "Tournament subject")
    private String subject;
    @Schema(name = "Tournament type")
    private String type;
    @Schema(name = "Team size")
    private Integer teamSize;
    @Schema(name = "Is tournament public")
    private Boolean isPublic;
}
