package ru.eljke.tournamentsystem.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

@Schema(name = "User Data Transfer Object")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserDTO {
    @Schema(name = "Autogenerated ID")
    private Long id;
    @Schema(name = "Username")
    private String username;
    @Schema(name = "User's fullname")
    private String fullname;
    @Schema(name = "User's date of birth")
    private String birthDate;
    @Schema(name = "User's city")
    private String city;
    @Schema(name = "User's school")
    private String school;
    @Schema(name = "User's grade")
    private String grade;
    @Schema(name = "User's roles")
    private String roles;
}
