package ru.eljke.tournamentsystem.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDate;
import java.util.Collection;
import java.util.Objects;
import java.util.Set;


@Schema(description = "Member details")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
public class Member implements UserDetails {
    @Schema(name = "Autogenerated ID", requiredMode = Schema.RequiredMode.REQUIRED)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;
    @Schema(name = "Member username", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "username", unique = true)
    @Size(min = 3, max = 16, message = "Username should be at least ${min} symbols")
    private String username;
    @Schema(name = "Member firstname", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "firstname")
    private String firstname;
    @Schema(name = "Member lastname", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "lastname")
    private String lastname;
    @Schema(name = "Member patronymic", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "patronymic")
    private String patronymic;
    @Schema(requiredMode = Schema.RequiredMode.REQUIRED, example = "dd/MM/yyyy")
    @JsonFormat(pattern = "dd/MM/yyyy")
    @PastOrPresent
    @Column(name = "birth_date")
    private LocalDate birthDate;
    @Column(name = "phone")
    private String phone;
    @Email
    @Column(name = "email")
    private String email;
    @Schema(name = "Member password", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "password")
    private String password;
    @Schema(name = "Member city", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "city")
    private String city;
    @Schema(name = "Member school", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "school")
    private String school;

    @Schema(name = "Member grade number", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonIgnore
    @Enumerated(EnumType.STRING)
    @Column(name = "grade_number")
    private GradeNumber gradeNumber;
    @Schema(name = "Member grade letter", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonIgnore
    @Enumerated(EnumType.STRING)
    @Column(name = "grade_letter")
    private GradeLetter gradeLetter;
    @Schema(name = "Member grade", requiredMode = Schema.RequiredMode.REQUIRED)
    @Column(name = "grade")
    private String grade;
    @Schema(name = "Member roles", requiredMode = Schema.RequiredMode.REQUIRED)
    @Enumerated(EnumType.STRING)
    @ElementCollection(fetch = FetchType.EAGER, targetClass = Role.class)
    @Column(name = "roles")
    private Set<Role> roles;

    public String getGrade() {
        if (getGradeNumber().getValue() != null && getGradeLetter() != null) {
            return String.valueOf(gradeNumber.getValue()) + gradeLetter;
        }

        return null;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Member member = (Member) o;
        return Objects.equals(id, member.id) && Objects.equals(username, member.username) && Objects.equals(firstname, member.firstname) && Objects.equals(lastname, member.lastname) && Objects.equals(patronymic, member.patronymic) && Objects.equals(birthDate, member.birthDate) && Objects.equals(phone, member.phone) && Objects.equals(email, member.email) && Objects.equals(password, member.password) && Objects.equals(city, member.city) && Objects.equals(school, member.school) && gradeNumber == member.gradeNumber && gradeLetter == member.gradeLetter && Objects.equals(grade, member.grade) && Objects.equals(roles, member.roles);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, username, firstname, lastname, patronymic, birthDate, phone, email, password, city, school, gradeNumber, gradeLetter, grade, roles);
    }

    @Override
    @JsonIgnore
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return roles;
    }

    @Override
    @JsonIgnore
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    @JsonIgnore
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    @JsonIgnore
    public boolean isEnabled() {
        return true;
    }

    @JsonIgnore
    public String getFullName() {
        return firstname + " " + lastname + " " + patronymic;
    }
}
